### ISSUE TITLE
Donkey Kong rbf not found

### ISSUE THREAD

**Issue by matijaerceg** [city41/AMMiSTer#125]
When I try to launch Donkey Kong, it seems that the rbf is not there.

I used the 'space' method to export to MiSTer.

**Comment by city41** [comment]
Ah yup, when looking at the details it is listing dk3 as its core. That seems like a bug.

![image](https://github.com/city41/AMMiSTer/assets/141159/30c38816-f59f-4ace-b011-ec7f1420e01c)

**Comment by city41** [comment]
I have this fixed in the dkbug branch but the integration tests are failing. I need to get that resolved which might take a bit.

I'll do the jtbeta thing too
