### ISSUE TITLE
Launch game on MiSTer from AMMiSTer

### ISSUE THREAD

**Issue by city41** [city41/AMMiSTer#7]
I *think* this is possible, but I'm not totally sure. If it is possible, add this in. 

If it is possible and feasible, this might be better than the MAME idea.

**Comment by exolon** [comment]
It is possible for other systems, not sure about MAME. There's an Android app that does it and it does list mame ROMs but I don't have my MiSTer with me to test it

**Comment by birdybro** [comment]
Definitely possible. Just have to inject the right command over ssh.

`echo load_core /media/fat/_Arcade/arcadegame.mra >/dev/MiSTer_cmd`

I *think* that will work, maybe.

**Comment by city41** [comment]
It looks like that only [works with cores](https://github.com/MiSTer-devel/Main_MiSTer/issues/190), not mras, sadly. My googling around so far has not found a way to launch an mra programmatically.

**Comment by birdybro** [comment]
Actually, it needs the corename and then the mra apparently

https://github.com/mrchrisster/MiSTer_SAM/blob/main/MiSTer_SAM_on.sh#L1550-L1551

**Comment by city41** [comment]
Ah ha, it does work! What was tripping me up was I was escaping the spaces in the file name, which `/dev/MiSTer_cmd`  doesn't seem to want.

This works
```
echo "load_core /media/fat/_Arcade/_foo/foo bar.mra" > /dev/MiSTer_cmd
```

This doesn't:
```
echo "load_core /media/fat/_Arcade/_foo/foo\ bar.mra" > /dev/MiSTer_cmd
```

Relative paths also work:

```
echo "load_core _Arcade/_foo/foo bar.mra" > /dev/MiSTer_cmd
```

Nice, this should be doable by AMMiSTer. Sadly it means adding SSH to the app, which doesn't work on MacOS :( but that is surmountable, just need to figure out a workaround for that.

**Comment by birdybro** [comment]
Maybe some clues in here for SSH.

https://github.com/electerm/electerm

Electron based like your app, MIT licensed, there might be some clues, supposedly works on Mac as well.

I would be highly suspicious if Macs didn't have some kind of SSH capability, that's unusual, it's a basic system administration tool, how would anyone do their job on it? :P

**Comment by city41** [comment]
Oh I meant the node ssh package causes an issue with macos and electron. I'll get macos and ssh working, especially now since this feature would be really cool.

btw, exporting to mister is done with ftp instead of ssh, as it's over twice as fast. ssh requires encryption, making the mister's lil cpu a bottleneck.

**Comment by city41** [comment]
v0.33.0 now includes short play videos thanks to Arcade Italia. So at least for now, I don't plan to implement this as I think the videos solve this need better.
