### ISSUE TITLE
Add Resolution criteria to Bulk Add

### ISSUE THREAD

**Issue by matijaerceg** [city41/AMMiSTer#70]
Requesting the ability to filter by resolutions as well, mainly for analog video output users.

It would be great for preparing folders that are compatible with my SD CRT TV, versus just using an HDMI digital display, versus using a 31kHZ CRT, etc

**Comment by city41** [comment]
That's a good idea. I'm not sure if resolution metadata is available? If it is, very easy to add. I'll take a look.

**Comment by city41** [comment]
Ahhh it is, yes the metadata has the refresh rate. I'll add this today.

**Comment by matijaerceg** [comment]
Yes, I think it'll just have 15khz and 31khz. Not sure if any titles use other resolutions.

The other thing to look into is splitting rotation into CCW and CW, like arcade organizer does, but I don't know if that info is available in the db

Thank you, can't wait to try using the resolution filter!

**Comment by city41** [comment]
Added in [v0.25.0](https://github.com/city41/AMMiSTer/releases)
