### ISSUE TITLE
Trash can broken

### ISSUE THREAD

**Issue by matijaerceg** [city41/AMMiSTer#78]
Looking at get started guide

https://github.com/city41/AMMiSTer/wiki/Getting-Started#deleting-games

I realize now that my question about the trash can in the discussions

https://github.com/city41/AMMiSTer/discussions/77

 seems to be a bug. Nothing happens when I click the trash can icon.

**Comment by matijaerceg** [comment]
This is on Win 10, version 0.25.0

**Comment by city41** [comment]
Ah yup, dumb mistake. I just fixed it and am cutting 0.25.1 right now. Will take about 15 minutes.
