### ISSUE TITLE
How does downloading of RBFs work?

### ISSUE THREAD

**Issue by city41** [city41/AMMiSTer#80]
### Discussed in https://github.com/city41/AMMiSTer/discussions/79

<div type='discussions-op-text'>

<sup>Originally posted by **matijaerceg** April 16, 2023</sup>
All the games in my list show the red icon, and show the rbf as missing. Does ammister not download the core files on catalog update?</div>

**Comment by city41** [comment]
@matijaerceg I am looking into this now

**Comment by matijaerceg** [comment]
More info:

Opening the catalog folder reveals that the rbf files do in fact exist:

![image](https://user-images.githubusercontent.com/4306199/232341177-c922c9d8-5d14-47ba-8157-6104856bd964.png)

This is on Win10, v0.25.0

**Comment by city41** [comment]
I am able to reproduce this on Windows. Should hopefully be a quick fix :crossed_fingers:

**Comment by matijaerceg** [comment]
Very cool, thank you!

**Comment by matijaerceg** [comment]
As a test, I deleted catalog.json in gameCache, and it did not fix the issue 

v 0.25.1

**Comment by city41** [comment]
This is fixed in v0.25.2, which will take about 15 minutes to show up on the releases.

This will require some steps to get your copy fixed:

- Install v0.25.2 or newer
- From AMMister's Catalog menu, select "open folder"
- delete the catalog.json file in the folder
- close AMMister and reopen it
- From AMMister's Catalog menu, choose "Check for updates..."
  - This will be a fast check, as it doesn't need to download much
  
 Let me know if that doesn't resolve it.

**Comment by city41** [comment]
ok, 0.25.2 is available. Can you let me know if this fixes it for you?

**Comment by matijaerceg** [comment]
yessir!

![image](https://user-images.githubusercontent.com/4306199/232346357-6ed6a3dd-1e07-484b-bd7b-eb03bca6ef87.png)
