### ISSUE TITLE
Space Mode: Exporting same plan repeatedly alternates between adding and deleting files

### ISSUE THREAD

**Issue by matijaerceg** [city41/AMMiSTer#84]
I have a test plan that just has all the street fighter games in a subfolder called Fighters. If I export this plan repeatedly without making any changes, every second time I run it, it deletes all the cores/roms/mras, and every other time it adds them back. 

Just ran it for the 4th time:
![image](https://user-images.githubusercontent.com/4306199/232349889-cefae672-e5c9-4f66-a523-380c0bd62fc0.png)

and here's my _Arcade contents now (empty):
![image](https://user-images.githubusercontent.com/4306199/232349919-652432bb-ddc7-4f7e-8446-4109c23b93b7.png)

**Comment by matijaerceg** [comment]
Just triple-confirming. Ran it for a 5th time (no changes to plan):
![image](https://user-images.githubusercontent.com/4306199/232350174-7cacbc79-0ddb-46a4-8669-3b22ddd7e543.png)

and the files are there now: 
![image](https://user-images.githubusercontent.com/4306199/232350207-bac746c0-31f6-4e41-84e1-988e439b5f52.png)

**Comment by matijaerceg** [comment]
By the way, this is all on Space mode (edited title to reflect this)

**Comment by matijaerceg** [comment]
Additional info: when I edit games between exports, it seems to add newly added ones, but delete the ones that were added the previous time.

**Comment by city41** [comment]
Can you go to Catalog > Open Folder. Then go up one folder and there should be files named "export-log--exportToMister...". Can you zip them all up and attach them here?

**Comment by matijaerceg** [comment]
The only files in the entire AppData > Roaming folder I see that contain the word log are:

![image](https://user-images.githubusercontent.com/4306199/232351281-c3e5374b-b9e6-48e2-b1e1-bcc44ed2ac1d.png)

**Comment by city41** [comment]
I clearly need to test on Windows more :)

I know what this is. This is due to Jotego dropping the dates from his core names. That broke AMMister and my fix was not good enough. Let me think a bit.

**Comment by matijaerceg** [comment]
haha yeah, gonna be lots of windows dummies using this I bet

Do you mostly use linux for daily use / testing?

**Comment by city41** [comment]
Yeah I use Linux. Thankfully OS specific issues are usually rare. Although that one you found where you can't edit the directory name, that seems like a bug in Windows itself. Not sure yet what I'll do about that one.

**Comment by matijaerceg** [comment]
That one seems pretty edge case, wouldn't worry about it too much

**Comment by city41** [comment]
The fix for this will be in 0.25.3 once it shows up. I also added an integration test to help ensure this doesn't happen again.
