### ISSUE TITLE
Three missing roms

### ISSUE THREAD

**Issue by matijaerceg** [city41/AMMiSTer#91]
These games show missing rom, as of sync just now:

Nova 2001
Pac-Man Plus
Magical Pumpkin:Puroland de Daibouken

**Comment by city41** [comment]
The rom download code was ported over from update_all. If update_all also can't find these roms, it's likely archive.org doesn't have them. If update_all can find these roms, then that is a bug in ammister.

**Comment by city41** [comment]
Ok update_all at least found magical pumpkin, so AMMister is behind here.

**Comment by city41** [comment]
update_all has a new rom db it uses. I just asked if it was ok to also use it in ammister. It would be a big improvement.

https://github.com/theypsilon/ArcadeROMsDB_MiSTer/issues/1

**Comment by city41** [comment]
Version 0.30.0 now uses theypsilon's rom db. If he doesn't want me to, I'll remove it and implement my own solution (only reason I'm a stickler on that is that db has no license).

* Magical Pumpkin: now downloaded
* Nova 2001: also missing in update_all, so not pursuing (at least not yet)
* Pac Man Plus: this is an hbmame rom, something AMMister does not support. It's now been removed from the catalog.

Nothing against hbmame, just haven't gotten there yet.

**Comment by theypsilon** [comment]
It was fine to use it. But I have to delete the repository. A new maintainer has its own one here https://github.com/BigDendy/ArcadeROMsDB_MiSTer which I guess you can use
